[workspace]
members = [
    "crates/json-rpc",
    "secure-rpc",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
futures = "0.3.30"
json-rpc = { path = "crates/json-rpc" }
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.37.0", default-features = false }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
pvde = { git = "https://github.com/radiusxyz/pvde", rev="0abc447e775a52ecc5695cf070086fcad9cdaebb"}
skde = { git = "https://github.com/radiusxyz/skde", rev="3549a4da49053394d3f1aef58ddd2ab416585bbb"}
sequencer = { git = "https://github.com/radiusxyz/sequencer", rev="1050571c3dab86593b6574385b4750c45ad27b22"}
radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev = "962f6b983a34826f8d03f8496c03d1a508f0207c", features = ["full"] }