[workspace]
members = [
    "crates/json-rpc",
    "secure-rpc",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
futures = "0.3.30"
json-rpc = { path = "crates/json-rpc" }
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.37.0", default-features = false }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
pvde = { git = "https://github.com/radiusxyz/pvde", rev="0abc447e775a52ecc5695cf070086fcad9cdaebb"}
skde = { git = "https://github.com/radiusxyz/skde", rev="13f18a4a6846795bb0ca20c4cd5ad494b7b6444f"}
sequencer = { git = "https://github.com/radiusxyz/sequencer", rev="76a55a547032c9156e57f7f3ad75ca24823632e8"}
radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev = "b48dee48c69c91e1a87c88499dcac98b44062ae9", features = ["full"] }
url = "2.5.2"