[workspace]
members = [
    "crates/json-rpc",
    "secure-rpc",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
futures = "0.3.30"
json-rpc = { path = "crates/json-rpc" }
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.37.0", default-features = false }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
pvde = { git = "https://github.com/radiusxyz/pvde", rev="0abc447e775a52ecc5695cf070086fcad9cdaebb"}
skde = { git = "https://github.com/radiusxyz/skde", rev="f8417e3611f58b7d38a85f209279d096efe0a378"}
sequencer = { git = "https://github.com/radiusxyz/sequencer", rev="3c9b37ac0f2d64f19d906ee7df292ed94856515c"}
radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev = "dd43cbcab85caeb1515c15f07019a94c83c724f7", features = ["full"] }
url = "2.5.2"