[workspace]
members = [
    "crates/json-rpc",
    "secure-rpc",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
futures = "0.3.30"
json-rpc = { path = "crates/json-rpc" }
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", default-features = false }
toml = "0.8.13"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
pvde = { git = "https://github.com/radiusxyz/pvde", rev="0abc447e775a52ecc5695cf070086fcad9cdaebb"}
radius-sequencer-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", rev = "34ef3b93a2833582123f5e963786d820f24eccf0", features = ["liveness-evm"] }
sequencer = { git = "https://github.com/radiusxyz/sequencer", branch="refactoring/encrypt-types"}