[package]
name = "secure-rpc-node-service"
version = "1.0.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
tracing.workspace = true

secure-rpc-primitives.workspace = true
secure-rpc-node-primitive.workspace = true
secure-rpc-service.workspace = true
radius-sdk.workspace = true
skde.workspace = true