[package]
name = "secure-rpc-provider"
version = "1.0.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "secure-rpc-provider"
path = "./main.rs"

[dependencies]

# Internal
secure-rpc-cli.workspace = true

# External
tracing-subscriber.workspace = true
anyhow.workspace = true
